language: julia
os:
    - osx
    - linux
julia:
    - 0.3
    - release
    - nightly
notifications:
    email: false

# Workaround for https://github.com/travis-ci/travis-ci/issues/4942
git:
  depth: 99999
